
package com.exampleTool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldImpltestService", targetNamespace = "http://example.com/", wsdlLocation = "http://localhost:9092/ws/hello?wsdl")
public class HelloWorldImpltestService
    extends Service
{

    private final static URL HELLOWORLDIMPLTESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDIMPLTESTSERVICE_EXCEPTION;
    private final static QName HELLOWORLDIMPLTESTSERVICE_QNAME = new QName("http://example.com/", "HelloWorldImpltestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9092/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDIMPLTESTSERVICE_WSDL_LOCATION = url;
        HELLOWORLDIMPLTESTSERVICE_EXCEPTION = e;
    }

    public HelloWorldImpltestService() {
        super(__getWsdlLocation(), HELLOWORLDIMPLTESTSERVICE_QNAME);
    }

    public HelloWorldImpltestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDIMPLTESTSERVICE_QNAME, features);
    }

    public HelloWorldImpltestService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDIMPLTESTSERVICE_QNAME);
    }

    public HelloWorldImpltestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDIMPLTESTSERVICE_QNAME, features);
    }

    public HelloWorldImpltestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImpltestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImpltestPort")
    public HelloWorld getHelloWorldImpltestPort() {
        return super.getPort(new QName("http://example.com/", "HelloWorldImpltestPort"), HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImpltestPort")
    public HelloWorld getHelloWorldImpltestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/", "HelloWorldImpltestPort"), HelloWorld.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDIMPLTESTSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDIMPLTESTSERVICE_EXCEPTION;
        }
        return HELLOWORLDIMPLTESTSERVICE_WSDL_LOCATION;
    }

}
